4.1 Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
# Simple Unit Converter

# Function to convert length
def convert_length(value, conversion_type):
    if conversion_type == 'm_to_ft':
        return value * 3.28084
    elif conversion_type == 'ft_to_m':
        return value / 3.28084
    else:
        print('Unsupported length conversion type.')
        return None

# Function to convert weight
def convert_weight(value, conversion_type):
    if conversion_type == 'kg_to_lbs':
        return value * 2.20462
    elif conversion_type == 'lbs_to_kg':
        return value / 2.20462
    else:
        print('Unsupported weight conversion type.')
        return None

# Function to convert volume
def convert_volume(value, conversion_type):
    if conversion_type == 'l_to_gal':
        return value * 0.264172
    elif conversion_type == 'gal_to_l':
        return value / 0.264172
    else:
        print('Unsupported volume conversion type.')
        return None

# Main program
print('Unit Converter')
print('Choose conversion type:')
print('1. Length (meters to feet or feet to meters)')
print('2. Weight (kilograms to pounds or pounds to kilograms)')
print('3. Volume (liters to gallons or gallons to liters)')

choice = input('Enter choice (1/2/3): ')
if choice not in ['1', '2', '3']:
    print('Invalid choice!')
else:
    try:
        value = float(input('Enter the value to convert: '))
        if choice == '1':
            conv_type = input("Enter conversion type ('m_to_ft' or 'ft_to_m'): ")
            result = convert_length(value, conv_type)
        elif choice == '2':
            conv_type = input("Enter conversion type ('kg_to_lbs' or 'lbs_to_kg'): ")
            result = convert_weight(value, conv_type)
        elif choice == '3':
            conv_type = input("Enter conversion type ('l_to_gal' or 'gal_to_l'): ")
            result = convert_volume(value, conv_type)

        if result is not None:
            print('Converted value:', result)
    except ValueError:
        print('Please enter a valid number!')


Unit Converter
Choose conversion type:
1. Length (meters to feet or feet to meters)
2. Weight (kilograms to pounds or pounds to kilograms)
3. Volume (liters to gallons or gallons to liters)
Enter choice (1/2/3): 1
Enter the value to convert: 55
Enter conversion type ('m_to_ft' or 'ft_to_m'): m_to_ft
Converted value: 180.4462


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [ ]:
# Simple Math Operations on a List of Numbers

# Function to calculate the sum of numbers
def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

# Function to calculate the average of numbers
def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    if len(numbers) == 0:
        print('Cannot calculate average of an empty list.')
        return None
    return sum(numbers) / len(numbers)

# Function to find the maximum value
def find_maximum(numbers):
    """Returns the maximum value from a list of numbers."""
    return max(numbers)

# Function to find the minimum value
def find_minimum(numbers):
    """Returns the minimum value from a list of numbers."""
    return min(numbers)

# Main program
print('Math Operations on a List of Numbers')
print('Choose an operation:')
print('1. Sum of numbers')
print('2. Average of numbers')
print('3. Maximum of numbers')
print('4. Minimum of numbers')

choice = input('Enter choice (1/2/3/4): ')
if choice not in ['1', '2', '3', '4']:
    print('Invalid choice!')
else:
    try:
        numbers = list(map(float, input('Enter numbers separated by spaces: ').split()))
        if len(numbers) == 0:
            print('The list of numbers cannot be empty!')
        else:
            if choice == '1':
                result = calculate_sum(numbers)
            elif choice == '2':
                result = calculate_average(numbers)
            elif choice == '3':
                result = find_maximum(numbers)
            elif choice == '4':
                result = find_minimum(numbers)

            if result is not None:
                print('Result:', result)
    except ValueError:
        print('Please enter valid numbers!')


Math Operations on a List of Numbers
Choose an operation:
1. Sum of numbers
2. Average of numbers
3. Maximum of numbers
4. Minimum of numbers
Enter choice (1/2/3/4): 1
Enter numbers separated by spaces: 6 7 8 
Result: 21.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):
    return lst[::2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print(output_list)  # Output: [1, 3, 5]


[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_list = get_sublist(input_list, start_index, end_index)
print(output_list)  # Output: [3, 4, 5]


[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

In [ ]:
def reverse_list(lst):
    return lst[::-1]

# Example usage:
input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)
print(output_list)  # Output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

# Example usage:
input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)
print(output_list)  # Output: [2, 3, 4]


[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(lst, n):
    return lst[:n]

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)
print(output_list)  # Output: [1, 2, 3]


[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 2
output_list = get_last_n(input_list, n)
print(output_list)  # Output: [4, 5]


[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print(output_list)  # Output: [5, 3, 1]


[5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [1]:
def flatten(lst):
    flattened_list = []
    for item in lst:
        if isinstance(item, list):
            flattened_list.extend(flatten(item))  # Recursively flatten if the item is a list
        else:
            flattened_list.append(item)
    return flattened_list

# Example usage:
nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))  # Output: [1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

In [2]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(lst, indices))  # Output: 6


6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [3]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum if the item is a list
        else:
            total += item
    return total

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))  # Output: 21


21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

In [4]:
def remove_element(lst, elem):
    # Iterate through the outer list and filter out the specified element from inner lists
    return [[item for item in sublist if item != elem] for sublist in lst]

# Example usage:
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(lst, elem)
print(result)  # Output: [[1], [3], [4, 5]]


[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [5]:
def find_max(lst):
    max_elem = float('-inf')  # Start with the lowest possible value

    for item in lst:
        if isinstance(item, list):
            max_elem = max(max_elem, find_max(item))  # Recursively find the max in sublists
        else:
            max_elem = max(max_elem, item)

    return max_elem

# Example usage:
lst = [[1, 2], [3, [4, 5]], 6]
result = find_max(lst)
print(result)  # Output: 6


6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

In [6]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in sublists
        elif item == elem:
            count += 1
    return count

# Example usage:
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(lst, elem)
print(result)  # Output: 3


3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [7]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # Recursively flatten nested lists
        else:
            flat_list.append(item)
    return flat_list

# Example usage:
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(lst)
print(result)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

In [8]:
def average_nested(lst):
    flat_list = []

    def flatten(lst):
        for item in lst:
            if isinstance(item, list):
                flatten(item)  # Recursively flatten nested lists
            else:
                flat_list.append(item)

    flatten(lst)

    # Calculate the average
    return sum(flat_list) / len(flat_list) if flat_list else 0

# Example usage:
lst = [[1, 2], [3, 4], [5, 6]]
result = average_nested(lst)
print(result)  # Output: 3.5


3.5


10 To - Do - NumPy
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [9]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4X2
ones_array = np.ones((4, 2))
print("\nAll ones array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value (e.g., 7)
filled_array = np.full((3, 3), 7)
print("\nArray filled with 7 (3x3):\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
existing_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(existing_array)
print("\nZeros array with the same shape as the given array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(existing_array)
print("\nOnes array with the same shape as the given array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted numpy array from list:", numpy_array)


Empty array (2x2):
 [[3.21983525e-316 0.00000000e+000]
 [6.90732054e-310 5.33257700e-317]]

All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array with the same shape as the given array:
 [[0 0]
 [0 0]]

Ones array with the same shape as the given array:
 [[1 1]
 [1 1]]

Converted numpy array from list: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_1 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_1)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix (0 to 8):\n", matrix_3x3)

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30 and its mean:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("\n10x10 Random array - Min value:", min_value, "Max value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts from 0, so 5th element is at index 4
print("\nZero array with 5th element replaced by 1:", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:", reversed_arr)

# 8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("1. Add the two arrays (x + y):\n", add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("\n2. Subtract the two arrays (x - y):\n", subtract_result)

# 3. Multiply the array with any integers of your choice
multiply_result = x * 2  # Multiply x by 2 (you can choose any integer)
print("\n3. Multiply the array x with 2:\n", multiply_result)

# 4. Find the square of each element of the array
square_result = np.square(x)
print("\n4. Square of each element in x:\n", square_result)

# 5. Find the dot product between:
# v and w
dot_vw = np.dot(v, w)
# x and v
dot_xv = np.dot(x, v)
# x and y
dot_xy = np.dot(x, y)
print("\n5. Dot product between:")
print("v and w:", dot_vw)
print("x and v:\n", dot_xv)
print("x and y:\n", dot_xy)

# 6. Concatenate x and y along the row and Concatenate v and w along the column
concatenate_xy_row = np.concatenate((x, y), axis=0)  # Concatenate x and y along rows
concatenate_vw_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Concatenate v and w along columns
print("\n6. Concatenate x and y along rows:\n", concatenate_xy_row)
print("Concatenate v and w along columns:\n", concatenate_vw_column)

# 7. Concatenate x and v; observe and explain why there's an error
try:
    concatenate_xv = np.concatenate((x, v), axis=0)
except Exception as e:
    print("\n7. Error while concatenating x and v along rows:", e)




Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [10]:
import numpy as np

# Matrix A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


In [11]:
# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
identity_matrix = np.dot(A, A_inv)

print("1. A.A−1 = I:\n", identity_matrix)


1. A.A−1 = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [12]:
# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. AB ≠ BA:")
print("AB:\n", AB)
print("BA:\n", BA)



2. AB ≠ BA:
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [13]:
# Compute the transpose of AB
AB_T = np.transpose(AB)

# Compute B^T * A^T
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

print("\n3. (AB)^T = B^T A^T:")
print("Transpose of AB:\n", AB_T)
print("B^T * A^T:\n", B_T_A_T)



3. (AB)^T = B^T A^T:
Transpose of AB:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]


In [14]:
# Coefficient matrix A
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Constants matrix B
B_eq = np.array([-1, -3, 9])

# Solve the system of linear equations AX = B using np.linalg.inv
X = np.linalg.inv(A_eq).dot(B_eq)

print("\n4. Solution of the linear system using inverse method:")
print("x, y, z:", X)



4. Solution of the linear system using inverse method:
x, y, z: [ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [16]:
import time
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
python_add_time = time.time() - start_time

array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
array_addition = array1 + array2
numpy_add_time = time.time() - start_time

**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [17]:
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
python_mul_time = time.time() - start_time

start_time = time.time()
array_multiplication = array1 * array2
numpy_mul_time = time.time() - start_time

**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [18]:
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
python_dot_time = time.time() - start_time

start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
numpy_dot_time = time.time() - start_time

**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [19]:
size_matrix = 1000
matrix1_np = np.arange(size_matrix**2).reshape(size_matrix, size_matrix)
matrix2_np = np.arange(size_matrix**2).reshape(size_matrix, size_matrix)

start_time = time.time()
matrix_multiplication_np = np.dot(matrix1_np, matrix2_np)
numpy_matrix_time = time.time() - start_time

In [20]:
print(f"Python Addition Time: {python_add_time:.5f} seconds")
print(f"NumPy Addition Time: {numpy_add_time:.5f} seconds")
print(f"Python Multiplication Time: {python_mul_time:.5f} seconds")
print(f"NumPy Multiplication Time: {numpy_mul_time:.5f} seconds")
print(f"Python Dot Product Time: {python_dot_time:.5f} seconds")
print(f"NumPy Dot Product Time: {numpy_dot_time:.5f} seconds")
print(f"NumPy Matrix Multiplication Time: {numpy_matrix_time:.5f} seconds")

Python Addition Time: 0.09518 seconds
NumPy Addition Time: 0.01096 seconds
Python Multiplication Time: 0.18855 seconds
NumPy Multiplication Time: 0.00835 seconds
Python Dot Product Time: 0.10048 seconds
NumPy Dot Product Time: 0.00332 seconds
NumPy Matrix Multiplication Time: 1.53060 seconds
